# Generated by Django 3.0.3 on 2020-09-07 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComercialNacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ComercialProvincial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DistribucionComercializadoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha de venta entre comercializadoras')),
                ('cantidad', models.IntegerField(default=0)),
                ('c_nacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.ComercialNacional')),
                ('c_provincial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.ComercialProvincial')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_produccion', models.DateTimeField(verbose_name='Fecha de Produccion')),
                ('fecha_caducidad', models.DateTimeField(verbose_name='Fecha de Caducidad')),
                ('lote', models.IntegerField(default=0)),
                ('dosis_bulbo', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sectores_Unidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('esquema_de_inmunizacion', models.CharField(max_length=1000)),
                ('tipo_ganado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VentaSectores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha de venta a sectores')),
                ('cantidad', models.IntegerField(default=0)),
                ('c_provincial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.ComercialProvincial')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.DistribucionComercializadoras')),
                ('sector_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.Sectores_Unidades')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(verbose_name='fecha de distribucion')),
                ('comercializadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.ComercialNacional')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.Productor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.Vacuna'),
        ),
        migrations.AddField(
            model_name='distribucioncomercializadoras',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.ProductoComercial'),
        ),
        migrations.CreateModel(
            name='AplicacionDeVacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha de aplicacion de vacuna')),
                ('cantidad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.VentaSectores')),
                ('sector_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.Sectores_Unidades')),
            ],
        ),
    ]
