# Generated by Django 3.0.3 on 2020-03-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaCompradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=1000)),
                ('organismo_al_que_pertence', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaVendedora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Ganado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_ganado', models.CharField(max_length=1000)),
                ('vacuna_que_se_le_aplica', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_compradora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.EmpresaCompradora')),
                ('empresa_vendedora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.EmpresaVendedora')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_de_la_dosis', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=1000)),
                ('esquema_de_inmunizacion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('ci', models.IntegerField(default=0)),
                ('experiencia_laboral', models.CharField(max_length=1000)),
                ('empresa_compradora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.EmpresaCompradora')),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_vendedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.EmpresaVendedora')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoComprado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_produccion', models.DateTimeField(verbose_name='fecha de produccion')),
                ('fecha_de_caducidad', models.DateTimeField(verbose_name='fecha de caducidad')),
                ('dosis_por_bulbo', models.IntegerField(default=0)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Produccion')),
            ],
        ),
        migrations.AddField(
            model_name='produccion',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Productor'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Vacuna'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Producto'),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.IntegerField(default=0)),
                ('empresa_compradora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.EmpresaCompradora')),
                ('empresa_vendedora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.EmpresaVendedora')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Fecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_compradora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.EmpresaCompradora')),
                ('ganado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Ganado')),
            ],
        ),
        migrations.CreateModel(
            name='Comercializdora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_vendedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD2Project.EmpresaVendedora')),
            ],
        ),
        migrations.CreateModel(
            name='AplicacionDeVacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis_aplicada', models.IntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Animal')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Fecha')),
                ('producto_comprado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.ProductoComprado')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Veterinario')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='ganado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BD2Project.Ganado'),
        ),
    ]
